version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    user: node
    volumes:
      - ./:/workspace
      - node-module-volume:/workspace/node_modules
      - next-volume:/workspace/.next
    working_dir: /workspace
    ports:
      - 3000:3000
    command: npm run dev
volumes:
  node-module-volume:
  next-volume:
